#!/bin/sh

# set secure umask
umask 0227

mkdir -p /run/nginx
chown -R nginx:nginx /run/nginx

if ! [ -f /etc/ssl/private/dh4096.pem ]; then
    openssl dhparam -out /etc/ssl/private/dh4096.pem 4096
fi

# set normal umask
umask 0022

cat > /etc/nginx/snippets/resolver <<EOF
resolver $(sed -n '/^nameserver /s///p' /etc/resolv.conf);
EOF
