#!/bin/sh

: ${nginx_default_hsts_max_age:=0}

mkdir -m 0755 -p /run/nginx
chown -R nginx:nginx /run/nginx

if ! [ -f /etc/ssl/nginx/dh4096.pem ]; then
    openssl dhparam -out /etc/ssl/nginx/dh4096.pem 4096
fi

umask 0022

mkdir -p /var/www/default/htdocs

cat > /etc/nginx/conf.d/default.conf <<EOF
server {
  listen 80 default;

  include snippets/headers;

  root /var/www/default/htdocs;

  location /.well-known {
  }

  location / {
    return 301 https://\$host\$request_uri;
  }
}

server {
  listen 443 ssl default;

  include snippets/headers;

  #ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
  #ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;

  $(
    if [ "$nginx_default_hsts_max_age" -gt 0 ]; then
      echo -n "add_header Strict-Transport-Security \""
      echo -n "max-age=$nginx_default_hsts_max_age; "
      echo "includeSubDomains\" always;"
    fi
  )

  root /var/www/default/htdocs;

  location / {
    $(
      if [ -n "$nginx_default_redirect" ]; then
        echo "return 301 $nginx_default_redirect;"
      elif [ -n "$nginx_default_proxy" ]; then
        echo "proxy_pass $nginx_default_proxy;"
      fi
    )
  }
}
EOF
